### ISSUE TITLE
9 vulnerabilities found ; Severity: 8 low | 1 high

### ISSUE THREAD

**Issue by fritserasmus** [Paul-Reed/node-red-contrib-simpletime#1]
I am not sure if I am doing something wrong, but I navigated to: 

> ~/.node-red

Then committed the following command:
$ `_npm install node-red-contrib-simpletime_`

And received this feedback:

> npm WARN node-red-project@0.0.1 No repository field.
> npm WARN node-red-project@0.0.1 No license field.
> 
> + node-red-contrib-simpletime@2.0.5
> added 1 package from 1 contributor in 5.825s
>        (!) 9 vulnerabilities found [133 packages audited]
>         Severity: 8 low | 1 high
>         Run `npm audit` for more detail

what did I do wrong?

**Comment by Paul-Reed** [comment]
You've done nothing wrong, and you will get the first 2 WARN messages with all node-red nodes because they are installed via npm.
The vulnerability report is a new feature added by npm, and is a report about all of your npm installed nodes, not just simpletime.
I'm not aware of any vulnerability in simpletime.
