### ISSUE TITLE
Year request.

### ISSUE THREAD

**Issue by Just-another-pleb** [Paul-Reed/node-red-contrib-simpletime#19]
Paul,

One thing which may be nice.

`msg.myyear` now gives  `"2020"`  which is fair enough.

But it would be nice if it could be cut to just `"20"`

**Comment by Paul-Reed** [comment]
The initial draft of simpletime was to create a lightweight, simple alternative to `moment`, but since then, it's grown in size as users want more formats for their user case.
I've given this a lot of thought over the past week or so, especially as `moment` has now been integrated into the node-RED core, which provides a much wider range of options, so I don't really want to bloat simpletime with features that can easily be created with `moment`.
I wrote a forum post about using `moment` with node-RED if it helps - https://discourse.nodered.org/t/formatting-times-dates-with-moment-js-examples/29553
